### ISSUE TITLE
Adaptação do sistema 

### ISSUE THREAD

**Issue by G2454** [G2454/tiosbriskeis-2024.1#2]
Temos algumas coisas dentro do site que não constam nas histórias de usuário.
Gostaria que vocês atualizassem os documentos caso percebam alguma coisa

**Comment by G2454** [comment]
Precisamos de uma história para Footer

**Comment by G2454** [comment]
Fazer a história de usuário para cards dos produtos que ao serem clicados levam para a parte específica na página de produtos

**Comment by fnlfds** [comment]
Acredito que seja também importante dar uma "geral" no github, pois me parece que existem coisas desnecessárias que foram criadas no passado e que ainda não foram usadas, além de alguns outros pormenores que podem existir(erros de português, títulos em locais errados, etc.) que são importantes de serem revisados para manter a padronização.
